// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bayu-aditya/quepters/internal/connector"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInputConnector creates a new instance of MockInputConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInputConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInputConnector {
	mock := &MockInputConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInputConnector is an autogenerated mock type for the InputConnector type
type MockInputConnector struct {
	mock.Mock
}

type MockInputConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInputConnector) EXPECT() *MockInputConnector_Expecter {
	return &MockInputConnector_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockInputConnector
func (_mock *MockInputConnector) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInputConnector_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockInputConnector_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockInputConnector_Expecter) Close() *MockInputConnector_Close_Call {
	return &MockInputConnector_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockInputConnector_Close_Call) Run(run func()) *MockInputConnector_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInputConnector_Close_Call) Return(err error) *MockInputConnector_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInputConnector_Close_Call) RunAndReturn(run func() error) *MockInputConnector_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Consume provides a mock function for the type MockInputConnector
func (_mock *MockInputConnector) Consume(ctx context.Context, process connector.ProcessFunc) error {
	ret := _mock.Called(ctx, process)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connector.ProcessFunc) error); ok {
		r0 = returnFunc(ctx, process)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInputConnector_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockInputConnector_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - process connector.ProcessFunc
func (_e *MockInputConnector_Expecter) Consume(ctx interface{}, process interface{}) *MockInputConnector_Consume_Call {
	return &MockInputConnector_Consume_Call{Call: _e.mock.On("Consume", ctx, process)}
}

func (_c *MockInputConnector_Consume_Call) Run(run func(ctx context.Context, process connector.ProcessFunc)) *MockInputConnector_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connector.ProcessFunc
		if args[1] != nil {
			arg1 = args[1].(connector.ProcessFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInputConnector_Consume_Call) Return(err error) *MockInputConnector_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInputConnector_Consume_Call) RunAndReturn(run func(ctx context.Context, process connector.ProcessFunc) error) *MockInputConnector_Consume_Call {
	_c.Call.Return(run)
	return _c
}
