// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOutputConnector creates a new instance of MockOutputConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutputConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutputConnector {
	mock := &MockOutputConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutputConnector is an autogenerated mock type for the OutputConnector type
type MockOutputConnector struct {
	mock.Mock
}

type MockOutputConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutputConnector) EXPECT() *MockOutputConnector_Expecter {
	return &MockOutputConnector_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockOutputConnector
func (_mock *MockOutputConnector) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutputConnector_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockOutputConnector_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockOutputConnector_Expecter) Close() *MockOutputConnector_Close_Call {
	return &MockOutputConnector_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockOutputConnector_Close_Call) Run(run func()) *MockOutputConnector_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOutputConnector_Close_Call) Return(err error) *MockOutputConnector_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutputConnector_Close_Call) RunAndReturn(run func() error) *MockOutputConnector_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Forward provides a mock function for the type MockOutputConnector
func (_mock *MockOutputConnector) Forward(ctx context.Context, data []byte) (bool, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Forward")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (bool, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) bool); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOutputConnector_Forward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forward'
type MockOutputConnector_Forward_Call struct {
	*mock.Call
}

// Forward is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockOutputConnector_Expecter) Forward(ctx interface{}, data interface{}) *MockOutputConnector_Forward_Call {
	return &MockOutputConnector_Forward_Call{Call: _e.mock.On("Forward", ctx, data)}
}

func (_c *MockOutputConnector_Forward_Call) Run(run func(ctx context.Context, data []byte)) *MockOutputConnector_Forward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutputConnector_Forward_Call) Return(ack bool, err error) *MockOutputConnector_Forward_Call {
	_c.Call.Return(ack, err)
	return _c
}

func (_c *MockOutputConnector_Forward_Call) RunAndReturn(run func(ctx context.Context, data []byte) (bool, error)) *MockOutputConnector_Forward_Call {
	_c.Call.Return(run)
	return _c
}
